name: Android CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify files
        run: |
          pwd
          ls -la
          find . -maxdepth 2 -name "gradlew"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Gradle Wrapper
        run: |
          cd "$GITHUB_WORKSPACE"
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: M-Energy-Debug-APK
          path: app/build/outputs/apk/debug/*.apk
